name: Release

on:
  # COMMENT for manually releasing versions
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  # UNCOMMENT for manually releasing versions
  workflow_dispatch:
    inputs:
      buildType:
        description: Type of build/release
        required: true
        type: choice
        options:
        - dev
        - hotfix

env:
  # Define git user email and name to be used for git commits
  GIT_USER_EMAIL: "actions@github.com"
  GIT_USER_NAME: "GitHub Actions"
  ENV_CONFIG_FILE: ".github/env-variables.txt"

jobs:
  release:
    runs-on: ubuntu-latest
    # COMMENT condition for manually releasing versions
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}